version: '3'

volumes:
  mysql_database:
    driver: local

services:
  mysql:
    image: library/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_database:/var/lib/mysql
#      - ./create_database.sh:/entrypoint.sh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: keycloak
      MYSQL_USER: project_a
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOSTNAME: mysql
    ports:
    - 3306:3306
    expose:
      - 3306


  keycloak:
    image: jboss/keycloak
    volumes:
      - ./assets/json/realm-export.json:/tmp/realm-export.json
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/tmp/realm-export.json"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: project_a
      DB_PASSWORD: ${DATABASE_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
#      KEYCLOAK_IMPORT_REALM: "/tmp/realm-export.json"
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8180:8080
    depends_on:
      - mysql

  api:
    build: .
    depends_on:
      - mysql
    ports:
      - 2424:2424
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}


